### ISSUE TITLE
Payoff Error

### ISSUE THREAD

**Issue by RubberArchind** [xendit/xendit-php#163]
PHP VERSION: 8.0.8

data params:{
    'external_id' => "payoff-764645313",    
    'amount' => 6000,
    'email' => "a.bgmail.com"
}

Error message:
Fatal error: Uncaught Xendit\Exceptions\ApiException: There was an error with the format submitted to the server. in sm\vendor\xendit\xendit-php\src\HttpClient\GuzzleClient.php:171 Stack trace: #0 sm\vendor\xendit\xendit-php\src\HttpClient\GuzzleClient.php(144): Xendit\HttpClient\GuzzleClient::_handleAPIError(Array) #1 sm\vendor\xendit\xendit-php\src\HttpClient\GuzzleClient.php(90): Xendit\HttpClient\GuzzleClient->_executeRequest(Array, '/payouts') #2 sm\vendor\xendit\xendit-php\src\ApiRequestor.php(84): Xendit\HttpClient\GuzzleClient->sendRequest('POST', '/payouts', Array, Array) #3 sm\vendor\xendit\xendit-php\src\ApiRequestor.php(43): Xendit\ApiRequestor->_requestRaw('POST', '/payouts', Array, Array) #4 sm\vendor\xendit\xendit-php\src\ApiOperations\Request.php(94): Xendit\ApiRequestor->request('POST', '/payouts', Array, Array) #5 sm\vendor\xendit\xendit-php\src\ApiOperations\Create.php(40): Xendit\Payouts::_request('POST', '/payouts', Array) #6 sm\withdraw.php(17): Xendit\Payouts::create(Array) #7 {main} thrown in sm\vendor\xendit\xendit-php\src\HttpClient\GuzzleClient.php on line 171

**Comment by RubberArchind** [comment]
I just realized that the minimum payoff is 10000
